== libthirdspacevest

by Kyle Machulis <kyle@nonpolynomial.com>
Nonpolynomial Labs - http://www.nonpolynomial.com

== Description

libthirdspacevest is an open-source, cross-platform (almost) driver
for the TN Games Third Space Vest. This vest uses pneumatic cells in
order to let gamers feel physical collisions from things like bullets
in first person shooters.

More information on the hardware can be found at

http://www.tngames.com

Information on the vest protocol, as well as the guide to reverse
engineering the vest and notes taken during the process, can be found
in the doc directory, or at

https://github.com/qdot/libthirdspacevest/blob/master/doc/third_space_vest_reverse_engineering.asciidoc

== Requirements

=== C Library

- CMake - http://www.cmake.org
- libusb-1.0 (Linux/OS X) - http://www.libusb.org
- WDK (Windows)

=== Python Library

- Python version 2.5 or greater - http://www.python.org
- PyUSB >= 1.0.a1 - http://sourceforge.net/apps/mediawiki/pyusb/index.php?title=Main_Page

== Future Plans

- Enumeration of effects provided in tngaming.lib

== Things to note

- The device will run without the air pump on. You won't get very hard
  hits, but it at least works for testing and is definitely audible.
- The maximum firing rate seems to be about 10hz, and that keeps the
  pump on constantly. I hate that pump so much.

== Platform Specifics

=== Linux

Until we get udev rules in, you'll probably need to run the script as
root. Additionally, since the device registers as HID, it'll have to
detach itself from the kernel driver. We already do this for you, and
we do not reattach afterward.

=== Mac OS X

You will need to install the "Third Space Vest OS X Extension" in
order to use this software on OS X. Copy the
ThirdSpaceVestNullDriver.kext into your /System/Library/Extensions
directory, and then either run 

kextload -- /System/Library/Extensions/ThirdSpaceVestNullDriver.kext

or else reboot your machine. After this, you should be able to run
either the C or python example and have the vest react appropriately.

=== Windows

When running CMake to generate the project on windows, you'll need to
set the WDK_PATH variable to the root of your WDK version, i.e.

C:\WinDDK\7600.16385.0

Also, this has only been successfully tested on VS2008. VS2010 seems
to break in odd ways due to the stdint.h. This will hopefully be
resolved soon.

== License ==

---------------------
Copyright (c) 2010, Kyle Machulis/Nonpolynomial Labs
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Kyle Machulis/Nonpolynomial Labs nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY Kyle Machulis/Nonpolynomial Labs ''AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Kyle Machulis/Nonpolynomial Labs BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE
---------------------
